var annotated_dup =
[
    [ "ConnectableResizer", "class_connectable_resizer.html", "class_connectable_resizer" ],
    [ "ConnectionSpecifications", "class_connection_specifications.html", "class_connection_specifications" ],
    [ "Diagram", "class_diagram.html", "class_diagram" ],
    [ "DiagramComponent", "class_diagram_component.html", "class_diagram_component" ],
    [ "DiagramConnection", "class_diagram_connection.html", "class_diagram_connection" ],
    [ "DiagramElement", "class_diagram_element.html", "class_diagram_element" ],
    [ "DiagramItem", "class_diagram_item.html", "class_diagram_item" ],
    [ "DiagramResizer", "class_diagram_resizer.html", "class_diagram_resizer" ],
    [ "DiagramSpecification", "class_diagram_specification.html", "class_diagram_specification" ],
    [ "DiagramType", "class_diagram_type.html", "class_diagram_type" ],
    [ "DiagramTypeGroup", "class_diagram_type_group.html", "class_diagram_type_group" ],
    [ "ElementSpecifications", "class_element_specifications.html", "class_element_specifications" ],
    [ "JsonFile", "class_json_file.html", "class_json_file" ],
    [ "JsonSerializable", "class_json_serializable.html", "class_json_serializable" ],
    [ "ListSpecification", "class_list_specification.html", "class_list_specification" ],
    [ "LongTextSpecification", "class_long_text_specification.html", "class_long_text_specification" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "ScrollableDataButtonsSelector", "class_scrollable_data_buttons_selector.html", "class_scrollable_data_buttons_selector" ],
    [ "SelectableDataButton", "class_selectable_data_button.html", "class_selectable_data_button" ],
    [ "SelectableSpecification", "class_selectable_specification.html", "class_selectable_specification" ],
    [ "ShortTextSpecification", "class_short_text_specification.html", "class_short_text_specification" ],
    [ "SpecificationsForm", "class_specifications_form.html", "class_specifications_form" ],
    [ "SpecificationsGroup", "class_specifications_group.html", "class_specifications_group" ],
    [ "Wizard", "class_wizard.html", "class_wizard" ]
];